FROM python:3.10

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        fonts-dejavu-core \
        fonts-dejavu-extra \
        libgl1 \
        libglib2.0-0 \
        build-essential && \
    fc-cache -fv && \
    rm -rf /var/lib/apt/lists/*

COPY ./backend/configs/requirements.txt ./backend/configs/requirements.txt
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r ./backend/configs/requirements.txt